
---
events:
  -
    kind: "message-v1"
    backtrace:
      - "C:/Users/v48305jm/AppData/Local/JetBrains/CLion 2024.1.2/bin/cmake/win/x64/share/cmake-3.28/Modules/CMakeDetermineSystem.cmake:233 (message)"
      - "CMakeLists.txt:16 (project)"
    message: |
      The system is: Windows - 10.0.19045 - AMD64
...
